package com.derkaiser.auth.service;

import com.derkaiser.auth.commons.dto.response.TokenResponse;
import com.derkaiser.auth.commons.model.entity.RefreshToken;
import com.derkaiser.auth.commons.model.entity.UserEntity;
import com.derkaiser.auth.commons.model.enums.UserRole;
import com.derkaiser.auth.repository.BlacklistedTokenRepository;
import com.derkaiser.auth.repository.RefreshTokenRepository;
import com.derkaiser.auth.service.impl.RefreshTokenServiceImpl;
import com.derkaiser.exceptions.auth.UserInactiveException;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.ArgumentCaptor;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.time.LocalDateTime;
import java.util.Optional;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
class RefreshTokenServiceImplTest {

    @Mock
    private RefreshTokenRepository refreshTokenRepository;

    @Mock
    private JwtService jwtService;

    @Mock
    private BlacklistedTokenRepository blacklistedTokenRepository;

    @InjectMocks
    private RefreshTokenServiceImpl refreshTokenService;

    private UserEntity user;
    private RefreshToken refreshToken;
    private final String refreshTokenString = "test-refresh-token";

    @BeforeEach
    void setUp() {
        user = UserEntity.builder()
                .id(UUID.randomUUID())
                .email("test@test.com")
                .role(UserRole.USER)
                .active(true)
                .verificatedEmail(true)
                .build();

        refreshToken = RefreshToken.builder()
                .id(UUID.randomUUID())
                .token(refreshTokenString)
                .userEntity(user)
                .expiryDate(LocalDateTime.now().plusDays(7))
                .build();
    }

    @Test
    void createRefreshToken_shouldCreateAndReturnToken() {
        when(jwtService.generateRefreshToken(anyString())).thenReturn(refreshTokenString);
        when(refreshTokenRepository.save(any(RefreshToken.class))).thenReturn(refreshToken);

        String tokenValue = refreshTokenService.createRefreshToken(user);

        assertEquals(refreshTokenString, tokenValue);
        verify(jwtService, times(1)).generateRefreshToken(user.getEmail());
        verify(refreshTokenRepository, times(1)).save(any(RefreshToken.class));
    }

    @Test
    void refreshAccessToken_shouldReturnNewAccessToken() {
        String newAccessToken = "new-access-token";
        String expectedNewRefreshToken = "generated-refresh-token"; // This will be generated by the actual method

        when(jwtService.validateToken(refreshTokenString)).thenReturn(true);
        when(refreshTokenRepository.findByTokenWithUser(refreshTokenString)).thenReturn(Optional.of(refreshToken));
        when(jwtService.generateAccessToken(user.getEmail(), user.getRole().name())).thenReturn(newAccessToken);
        when(jwtService.generateRefreshToken(user.getEmail())).thenReturn(expectedNewRefreshToken);
        when(refreshTokenRepository.save(any(RefreshToken.class))).thenReturn(
            RefreshToken.builder()
                .id(UUID.randomUUID())
                .token(expectedNewRefreshToken)
                .userEntity(user)
                .build()
        );

        TokenResponse response = refreshTokenService.refreshAccessToken(refreshTokenString);

        assertNotNull(response);
        assertEquals(newAccessToken, response.getAccessToken());
        assertEquals(expectedNewRefreshToken, response.getRefreshToken()); // Should return the new refresh token
        verify(jwtService, times(1)).generateAccessToken(user.getEmail(), user.getRole().name());
        verify(jwtService, times(1)).blacklistToken(refreshTokenString, "REFRESH"); // Old token should be blacklisted
        verify(refreshTokenRepository, times(1)).delete(refreshToken); // Old token should be deleted from DB
        verify(jwtService, times(1)).generateRefreshToken(user.getEmail()); // New token should be generated
        verify(refreshTokenRepository, times(1)).save(any(RefreshToken.class)); // New refresh token should be saved
    }

    @Test
    void refreshAccessToken_shouldThrowExceptionForInvalidJwt() {
        when(jwtService.validateToken(refreshTokenString)).thenReturn(false);

        IllegalArgumentException exception = assertThrows(IllegalArgumentException.class,
                () -> refreshTokenService.refreshAccessToken(refreshTokenString));

        assertEquals("Refresh token inválido o expirado", exception.getMessage());
        verify(refreshTokenRepository, never()).findByTokenWithUser(anyString());
    }

    @Test
    void refreshAccessToken_shouldThrowExceptionWhenTokenNotFoundInDb() {
        when(jwtService.validateToken(refreshTokenString)).thenReturn(true);
        when(refreshTokenRepository.findByTokenWithUser(refreshTokenString)).thenReturn(Optional.empty());

        IllegalArgumentException exception = assertThrows(IllegalArgumentException.class,
                () -> refreshTokenService.refreshAccessToken(refreshTokenString));

        assertEquals("Refresh token no encontrado", exception.getMessage());
    }

    @Test
    void refreshAccessToken_shouldThrowExceptionAndDeletesWhenTokenIsExpiredInDb() {
        refreshToken.setExpiryDate(LocalDateTime.now().minusDays(1));
        when(jwtService.validateToken(refreshTokenString)).thenReturn(true);
        when(refreshTokenRepository.findByTokenWithUser(refreshTokenString)).thenReturn(Optional.of(refreshToken));

        IllegalArgumentException exception = assertThrows(IllegalArgumentException.class,
                () -> refreshTokenService.refreshAccessToken(refreshTokenString));

        assertEquals("Refresh token expirado. Por favor, inicia sesión nuevamente", exception.getMessage());
        verify(refreshTokenRepository, times(1)).delete(refreshToken);
        verify(jwtService, times(1)).blacklistToken(refreshTokenString, "REFRESH"); // Should blacklist expired token
    }

    @Test
    void refreshAccessToken_shouldThrowExceptionAndDeletesWhenUserIsInactive() {
        user.setActive(false);
        when(jwtService.validateToken(refreshTokenString)).thenReturn(true);
        when(refreshTokenRepository.findByTokenWithUser(refreshTokenString)).thenReturn(Optional.of(refreshToken));

        com.derkaiser.exceptions.auth.UserInactiveException exception = assertThrows(UserInactiveException.class,
                () -> refreshTokenService.refreshAccessToken(refreshTokenString));

        assertEquals("Tu cuenta no está activa", exception.getMessage());
        verify(refreshTokenRepository, times(1)).delete(refreshToken);
        verify(jwtService, times(1)).blacklistToken(refreshTokenString, "REFRESH"); // Should blacklist invalid token
    }

    @Test
    void deleteByToken_shouldDeleteTokenWhenFound() {
        when(refreshTokenRepository.findByTokenWithUser(refreshTokenString)).thenReturn(Optional.of(refreshToken));
        doNothing().when(refreshTokenRepository).delete(refreshToken);

        refreshTokenService.deleteByToken(refreshTokenString);

        verify(refreshTokenRepository, times(1)).findByTokenWithUser(refreshTokenString);
        verify(refreshTokenRepository, times(1)).delete(refreshToken);
    }

    @Test
    void deleteByToken_shouldDoNothingWhenTokenNotFound() {
        when(refreshTokenRepository.findByTokenWithUser(refreshTokenString)).thenReturn(Optional.empty());

        refreshTokenService.deleteByToken(refreshTokenString);

        verify(refreshTokenRepository, times(1)).findByTokenWithUser(refreshTokenString);
        verify(refreshTokenRepository, never()).delete(any());
    }

    @Test
    void cleanExpiredTokens_shouldCallRepositoryMethod() {
        doNothing().when(refreshTokenRepository).deleteExpiredTokens(any(LocalDateTime.class));
        doNothing().when(blacklistedTokenRepository).deleteExpiredTokens(any(LocalDateTime.class));

        refreshTokenService.cleanExpiredTokens();

        ArgumentCaptor<LocalDateTime> captor = ArgumentCaptor.forClass(LocalDateTime.class);
        verify(refreshTokenRepository, times(1)).deleteExpiredTokens(captor.capture());
        verify(blacklistedTokenRepository, times(1)).deleteExpiredTokens(captor.capture());
        assertNotNull(captor.getValue());
    }
}